[project]
name = "router-fingerprinting"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "beautifulsoup4>=4.13.4",
    "cvss==3.4",
    "pandas>=2.2.3",
    "requests>=2.32.3",
]
